dist: xenial
services:
- postgresql
sudo: required
addons:
  postgresql: '9.4'
  chrome: stable
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
- CHROME_MAIN_VERSION=`google-chrome-stable --version | sed -E 's/(^Google Chrome
  |\.[0-9]+ )//g'`
- CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAIN_VERSION"`
- curl "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
  -O
- unzip chromedriver_linux64.zip -d ~/bin
language: python
python:
- '3.6'
install:
- wget https://github.com/mozilla/geckodriver/releases/download/v0.27.0/geckodriver-v0.27.0-linux64.tar.gz
- tar -xzf geckodriver-v0.27.0-linux64.tar.gz
- chmod +x geckodriver
- sudo cp geckodriver /usr/bin/
- pip install -r requirements.txt
- pip install codacy-coverage
script:
- cd decide
- cp travis_local_settings.py local_settings.py
- cd decide
- cp travis_settings.py settings.py
- cd ..
- coverage run --branch --source=. ./manage.py test voting --keepdb
- coverage xml
- python-codacy-coverage -r coverage.xml
deploy:
  provider: heroku
  app: guadalfeo-votaciones-prod
  strategy: git
  api_key:
    secure: CB4UBNY4gKTHdw825Vhvw63SSg/JHiaqBvKXAt175VPcBkgls1RJyqdw0yYXWW1yvsp+ViPimmHrXC+cFDsgo/SBvLm7Qwswm7w27LfF2H5eZkAx+3ZLMmFdqFMbTcCJitpoJMdk9e/b+LR8eHPPru9s4CTF7imGEeerAPxZQB6eqH+LjpidO4/XmZvGHtQ4LGJFG4tk6ISLNzhW4qzSmu4nSFwekfx6j0VXE4PeO5nmxv0lwGn1VEavcxfc9k/LfFiPQB03QivPscFSJHwCl2LNO+Rk3k3RVlIulurggDEZf1SQo9PGtm62h48GT54e3DaxhIR/vqiSuVURdAzHtEMH+Kj+al1s+WNYirbiFFiywvZt29E3wRpr+qCX94FozNJVWW7gYFgGkdSqZXzayzeIsBW3AcN7YMV8OlymkPVp4MqJRGEoqvcWEnZEqoEC2njUnZcvB94ECeLofd0bntpIsssjAJup1j5Fm6RtY4FalK+/Npg4ZzRjyw3Yks5CaQ/joVCZa9bBDar6mJAao51Hnr10THg5N/wv5Nb7s9mLJEspMukYF4aBzCYGq8hsVOoiSFVDwolOS6WfLzp4XtiSH9A3/wiV5ZR1Fy5+peFW01XKBCwhJ/DUiSiPXxGuUi/K7fvHNcMoFxeVvxpyj8ydc9TxsgAAQhWCQOFH9Wk=
  on:
    branch: hotfix/1.0.0
