# Generated by Django 2.0 on 2020-12-11 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_candidatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='candiancy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voting', to='voting.Candidatura'),
        ),
        migrations.AddField(
            model_name='voting',
            name='tipo',
            field=models.TextField(choices=[('PV', 'Primary voting'), ('GV', 'General voting')], default='PV'),
        ),
    ]
